### ISSUE TITLE
How to style default input?

### ISSUE THREAD

**Issue by jimmiejackson414** [wheredoesyourmindgo/react-mui-mapbox-geocoder#1]
Hey there, thanks for the awesome library!

I'm using material-ui's outlined inputs across my app. Is there a way to specify the type of input I want to use? Or better yet, use my existing (nonfunctioning) styled input with your library?

<img width="490" alt="Screen Shot 2019-03-10 at 9 06 35 AM" src="https://user-images.githubusercontent.com/10987731/54086108-ebbd4480-4313-11e9-8a3c-15e1c67966ad.png">

Any thoughts on how to fix this? Thanks!

**Comment by jimmiejackson414** [comment]
FYI I've edited my original question because I discovered that the issue with the strange-looking results was because of two things: specifying proximity and bbox in my geocoderOptions object was only returning results in that area; i also had some styles that were overriding the results dropdown.

I do have remaining questions about how to best style your default input to match the rest of my app. Thank you!

**Comment by wheredoesyourmindgo** [comment]
Thanks for the feedback @jimmiejackson414 
Re: First Question - What options are you using for the geocoder? If you are passing `proximity` or `bbox` I could see that the issue might arise from there. Coincidentally I live in that locale that you have shown in your screenshot so I wonder if code from source I used in the demo folder made it's way into your working example in some way or another.

**Comment by wheredoesyourmindgo** [comment]
Oh. Okay. You figured that one out already.

Re: Second Question - Are you using JSS as a styling solution with your project?

**Comment by jimmiejackson414** [comment]
For larger styling needs I'm using styled-components, and for one-off styling I use the JSS that is part of material-ui.

**Comment by wheredoesyourmindgo** [comment]
Can you try upgrading to version 0.4.0 and adding the following props to <MatGeocoder/> ?

```
inputTextFieldProps={{
              variant: 'outlined',
              fullWidth: false,
              classes: {
                root: classes.textField
              }
            }}
    inputClasses={{root: classes.input}}
    showInputContainer={false}
```

and add the following JSS styles to your component that contains the <MatGeocoder/> component?
```
const styles = {
  input: {
    backgroundColor: 'white',
    borderRadius: 3
  },
  textField: {
    width: '100%'
  }
};
```

Does that look like what you are trying to achieve?

**Comment by wheredoesyourmindgo** [comment]
Yes I agree with "Or better yet, use my existing (nonfunctioning) styled input with your library?" I think that would be a good direction for this component. Admittedly the way I set this component up seemed re-usable at the time, but in reflection it is hard to customize.

**Comment by jimmiejackson414** [comment]
Thanks for working out an update! I appear to be getting some breaking-page errors though, and I'm working to determine whether it's an issue with the library or some issue with my code. My component is getting quite complex so it very easily could be that. If I figure out the cause though I'll update this thread.

<img width="1335" alt="Screen Shot 2019-03-11 at 6 44 49 PM" src="https://user-images.githubusercontent.com/10987731/54165232-cfadc600-442d-11e9-9769-a047f36ecd62.png">

**Comment by wheredoesyourmindgo** [comment]
Is your project public? Can I clone any repo so that I can reproduce it? Are you using React 16.8+? I happened to update the component to use the new Hooks API so that could have broke your component.

**Comment by jimmiejackson414** [comment]
Ah there it is! I had React 16.0, so I just upgrade to the latest and now it all works. Looks absolutely perfect too, I can just style it to exactly match my others. Thanks for your responsiveness!

**Comment by wheredoesyourmindgo** [comment]
Of course. Thanks for using the component and contributing here.
