### ISSUE TITLE
How to target fieldset of input?

### ISSUE THREAD

**Issue by jimmiejackson414** [wheredoesyourmindgo/react-mui-mapbox-geocoder#2]
Hi there, me again.

Apologies for my ignorance... I'm having a bit of trouble figuring out how to target the fieldset inside of the input style. For me, it has a "NotchedOutline" class.

<img width="395" alt="Screen Shot 2019-03-28 at 8 28 21 PM" src="https://user-images.githubusercontent.com/10987731/55203069-19b9da00-5198-11e9-9171-adcb23ffbe9b.png">

More specifically, I need to alter the blue border when the input has focus.

<img width="552" alt="Screen Shot 2019-03-28 at 8 29 37 PM" src="https://user-images.githubusercontent.com/10987731/55203099-3a822f80-5198-11e9-8e90-da46bf9f86fe.png">

My code is as follows:
`const Geocoder = withStyles({`
  `container: {`
`    backgroundColor: 'inherit',`
`    marginTop: '16px',`
`  },`
`})(MatGeocoder);`

`const styles = {`
`  input: {`
  `  '&$cssFocused $notchedOutline': {`
    `  backgroundColor: 'green'`
`    }`
`  },`
`  textField: {`
  `  // backgroundColor: 'blue',`
`  }`
`};`

`<Geocoder`
  `     inputPlaceholder='City, State'`
   `    accessToken={MAPBOX_TOKEN}`
    `   onSelect={result => this._handleChange}`
    `   showLoader={true}`
    `   inputPaperProps={{ square: true }}`
    `   suggestionsPaperProps={{`
     `      square: true,`
       `  }}`
        ` inputTextFieldProps={{`
         `    variant: 'outlined',`
           `  fullWidth: true,`
             `classes: {`
               `  root: classes.textField`
           `  }`
        ` }}`
         `inputClasses={{`
          `   root: classes.input`
         ` }}`
         ` showInputContainer={false}`
         ` {...geocoderOptions}`
   `>`
`</Geocoder>`

Thanks for your help!

**Comment by wheredoesyourmindgo** [comment]
Yes, that is a bit cryptic.

Try:
```javascript
const styles = {
    input: {
        '&$cssFocused $notchedOutline': {
            borderColor: 'green'
        }
    },
    notchedOutline: {},
    cssFocused: {},
    textField: {
        // backgroundColor: 'blue',
    }
};
```

and

```javascript
inputClasses={{
    root: classes.input,
    notchedOutline: classes.notchedOutline,
    focused: classes.cssFocused
}}           
```



See [this Material-UI Issue](https://github.com/mui-org/material-ui/issues/13347) for more info regarding the complexity surrounding the targeting/styling this component.

**Comment by jimmiejackson414** [comment]
Ah I see! In my normal TextField's those classes would've been applied to InputLabelProps and InputProps. So now i've been able to fix it with something like this:
`inputClasses={{
                root: classes.cssOutlinedInput,
                focused: classes.cssFocused,
                notchedOutline: classes.notchedOutline,
              }}`

Thanks for the help!
