### ISSUE TITLE
Set default value

### ISSUE THREAD

**Issue by spiotrowska** [wheredoesyourmindgo/react-mui-mapbox-geocoder#3]
Is it possible to set default value into textfield?

**Comment by wheredoesyourmindgo** [comment]
@spiotrowska Try updating to version 0.4.17 and passing a `inputValue` prop to this component.

**Comment by spiotrowska** [comment]
@wheredoesyourmindgo  It works, thank you.
Now I have one more problem. I want to rerender `<MatGeocoder>` component when `inputVaue` was changed. I think it should works with my code:

`<MatGeocoder
            accessToken={mapBoxToken}
            onSelect={result => 
              props.setUserLocation({
                lat: result.geometry.coordinates[1], 
                lng: result.geometry.coordinates[0]
              })
            }
            showLoader={true}
            **inputValue={userLocationInputValue}**
            inputTextFieldProps={{
              classes: {
                root: classes.textField
              }
            }}
            inputClasses={{ root: classes.input }}
            showInputContainer={false}
          />`

Variable `userLocationInputValue` is from state.
Do you have any idea?

**Comment by spiotrowska** [comment]
@wheredoesyourmindgo  I think you should delete useMemo from const autoSuggestEl.
Is it possible? Could you do that?

**Comment by pcwa-ahendricks** [comment]
@spiotrowska I see what you mean. I set that up to behave more like an initial/defaulted value rather than a property that the input would bind to. Sadly my development environment is not working and I'm at my wits end for now trying to figure out why; I posted a new version 0.4.19. Can you update the lib to that version and see if it yields to correct behavior?

**Comment by pcwa-ahendricks** [comment]
> `autoSuggestEl`

Is this comment related to the previous?

**Comment by spiotrowska** [comment]
@pcwa-ahendricks  I thought `useMemo` was the reason of my problem. It doesn't matter.
I upgraded version and it works! Thank you very much.
