### ISSUE TITLE
UX: text field and cross are too far and cannot make them closer

### ISSUE THREAD

**Issue by clementlize** [wheredoesyourmindgo/react-mui-mapbox-geocoder#30]
Hi there, thanks for the library.

I spent one hour on a UI-UX bug and I couldn't make it work. In mobile view, the space between the textflield and the cross is too large. This is due to padding inside the component and I couldn't set them to 0 with the properties I can access.

Here is a picture, a bug part of the address is truncated because of this space.

![bug_matgeocoder](https://user-images.githubusercontent.com/48858570/123390496-463d4600-d59b-11eb-9432-5a003ad940a7.jpg)

Can you make this space a parameter? Thanks !

**Comment by wheredoesyourmindgo** [comment]
Nice. I will fix that and reply back once its updated

>

**Comment by pcwa-ahendricks** [comment]
We should be good now. Not sure why the <Grid/> component was ever using that much padding

**Comment by clementlize** [comment]
Thanks I will try to test it. By the way, there is no instruction on how to install the module, and the package on npm has last been updated... 3 years ago..

Do you deploy it somewhere else?

https://www.npmjs.com/package/react-mui-mapbox-geocoder-emp

**Comment by wheredoesyourmindgo** [comment]
That looks like an older version of this component that was published by someone else.  Use the component found in 
[https://www.npmjs.com/package/react-mui-mapbox-geocoder](https://www.npmjs.com/package/react-mui-mapbox-geocoder). Also, I fixed the Readme so that should show up on npmjs.com now.

npm install --save react-mui-mapbox-geocoder

If you are using a Typescript in your project another option is to copy/paste the code from the github repo.

**Comment by clementlize** [comment]
Okay, thank you! The old npm package was the first result when I searched for the library, so now I think with the readme people will see the good one.

I tested it today and now everything's fine. 
Thanks and keep it up!

**Comment by wheredoesyourmindgo** [comment]
I will try. The honest truth is the development process is getting the best of me sadly. I’ve spent a few hours on putting this component together, and I have logged countless hours trying to figure out how to redistribute it via npm using rollup, webpack, babel, microbundle,… all the while I didn’t feel like I learned anything in all the effort spent there. In retrospect, it would have been easier (time saving) to simply copy/paste this component from project to project as needed.

You are most welcome. Thanks for the feedback, encouragement, and for opening this issue.

**Comment by clementlize** [comment]
Well, by distributing on npm you saved my team from some possible mistakes. The code is in a node_module and we only track it by the package.json file. Everyone has it when the commit is checked out and there is no doubt or mistake possible.

By copy-pasting, we assume that this code is ours (well not really but that's the idea) and maybe one day someone will find it and try to edit it or think we wrote it. It seems the probability is low but well, the concept of a node module is better.

Sorry to hear that it took you ages, isn't there any way to make this a bit more automatic? And thank you very much for your effort
