### ISSUE TITLE
Add ref

### ISSUE THREAD

**Issue by spiotrowska** [wheredoesyourmindgo/react-mui-mapbox-geocoder#4]
Is it possible to add ref to this component? It returns error below:

Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Comment by pcwa-ahendricks** [comment]
@spiotrowska There is a good overview of forwardRef here. [https://reactjs.org/docs/forwarding-refs.html](https://reactjs.org/docs/forwarding-refs.html ) Using forwardRef with this Function Component should make the console warning go away.
