### ISSUE TITLE
[Feature]: let the user chose between a <InputBase /> and a <TextField />

### ISSUE THREAD

**Issue by clementlize** [wheredoesyourmindgo/react-mui-mapbox-geocoder#56]
Hello again! 

Some days ago I identified a feature that I needed for my project, and thought I could make it a merge request for it. I don't know if you get notifications for merge requests, so I am writing an issue too :)

As it is, the component does not have anything to indicate to the user that the field is a field, more than the search icon and the placeholder. So I needed the MUI v4 search field design back (with the underline). And maybe other people would like their input to have a border, like when using the "outlined" variant.

The idea of my implementation is to let the user chose whether they want to use an `<InputBase /> `or a `<TextField />`.

The changes I made do not break the component, apart from the removal of the disableUnderline property (which was not used anywhere in the code). Indeed, by default the `<InputBase />` is used, and does not have any border or underline. Maybe this removal is not a great thing, I'll let you decide :smile: 

For my use case (in my project), I just have to rename inputProps into textFieldProps, and add "variant: standard" to get the MUI v4 design back.

If you want me to explain more, or want to talk about this feature, feel free :)
https://github.com/wheredoesyourmindgo/react-mui-mapbox-geocoder/pull/55

**Comment by wheredoesyourmindgo** [comment]
interesting. i will take a look early next week at this pull request.

Abe
