### ISSUE TITLE
building typescript

### ISSUE THREAD

**Issue by joelondon** [wheredoesyourmindgo/react-mui-mapbox-geocoder#9]
https://github.com/wheredoesyourmindgo/react-mui-mapbox-geocoder/blob/0f4b4a4bdea664bdd1f2edd4f617f2e0d694b23e/src/MatGeocoder/MatGeocoder.tsx#L400

nice component :) building the typescript is proving tricky as the `classes` inputProp to the `Autosuggest` tag provokes a `No overload matches this call.` error, any tips?

**Comment by wheredoesyourmindgo** [comment]
I think I can re-produce that problem. I will take a look and see if I can't fix that.

**Comment by wheredoesyourmindgo** [comment]
Try upgrading to the latest version of this library via npm and see if your issue goes away.

**Comment by joelondon** [comment]
that worked, thanks :)
